# Supabase credentials
supabase_url = "https://bskykszrjuxvqxgngnir.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJza3lrc3pyanV4dnF4Z25nbmlyIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczODI1MzUxNCwiZXhwIjoyMDUzODI5NTE0fQ.ePaEN8zC6o7GwmI72W4ABSWRya_93R1HY_OnQY-QxyA"



